name: marvel_api_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  bloc_pattern: ^3.0.1
  http: any
  crypto: ^3.0.2
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: MarvelRegular
      fonts:
        - asset: assets/fonts/marvelregular.ttf

    - family: AvangersRegular
      fonts:
        - asset: assets/fonts/avangersregular.ttf
